/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author netoh
 */
public class login_GUI extends javax.swing.JFrame {

    /**
     * Creates new form login_GUI
     */
    public login_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscacpf_txt = new javax.swing.JTextField();
        buscapassword_txt = new javax.swing.JTextField();
        btnbusca = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscacpf_txt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPF:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        buscacpf_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscacpf_txtActionPerformed(evt);
            }
        });
        getContentPane().add(buscacpf_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 280, 40));

        buscapassword_txt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        buscapassword_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscapassword_txtActionPerformed(evt);
            }
        });
        getContentPane().add(buscapassword_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 280, 40));

        btnbusca.setText("Enviar");
        btnbusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscaMouseExited(evt);
            }
        });
        btnbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaActionPerformed(evt);
            }
        });
        getContentPane().add(btnbusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, 40));

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 80, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menubg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscacpf_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscacpf_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscacpf_txtActionPerformed

    private void buscapassword_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscapassword_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscapassword_txtActionPerformed

    private void btnbuscaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscaMouseEntered
        btnbusca.setBackground(new java.awt.Color(0,128,0));
        btnbusca.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnbuscaMouseEntered

    private void btnbuscaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscaMouseExited
        btnbusca.setBackground(new java.awt.Color(240,240,240));
        btnbusca.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnbuscaMouseExited

    private void btnbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaActionPerformed
        String nomeUsuario = Model.Functions_DAO.validateUser();
if(nomeUsuario != null){
    JOptionPane.showMessageDialog(null, "Bem vindo, " + nomeUsuario);
    dispose();
    new inicio_GUI().setVisible(true);
} else {
    JOptionPane.showMessageDialog(null, "Usuário não encontrado ou senha incorreta, tente novamente!");
}


    }//GEN-LAST:event_btnbuscaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new menu_GUI().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbusca;
    public static javax.swing.JTextField buscacpf_txt;
    public static javax.swing.JTextField buscapassword_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
