/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author netoh
 */


    import Controller.Database;
    import Controller.Oceans;
    import java.util.ArrayList;

public class Oceanos_GUI extends javax.swing.JFrame {
    
    public static ArrayList<Oceans> oceans = new ArrayList<>();

    /**
     * Creates new form Oceanos
     */
   public Oceanos_GUI() {
    oceans = new Database().oceans;
    initComponents();
    loading(); 
}
    
   public static void loading(){
        nomeoceano1_txt.setText(oceans.get(0).name);
        nomeoceano2_txt.setText(oceans.get(1).name);
        nomeoceano3_txt.setText(oceans.get(2).name);
        nomeoceano4_txt.setText(oceans.get(3).name);
        nomeoceano5_txt.setText(oceans.get(4).name);

        phoceano1_txt.setText(String.valueOf(oceans.get(0).pH));
        phoceano2_txt.setText(String.valueOf(oceans.get(1).pH));
        phoceano3_txt.setText(String.valueOf(oceans.get(2).pH));
        phoceano4_txt.setText(String.valueOf(oceans.get(3).pH));
        phoceano5_txt.setText(String.valueOf(oceans.get(4).pH));   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeoceano3_txt = new javax.swing.JLabel();
        nomeoceano2_txt = new javax.swing.JLabel();
        nomeoceano4_txt = new javax.swing.JLabel();
        nomeoceano5_txt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        phoceano1_txt = new javax.swing.JLabel();
        phoceano3_txt = new javax.swing.JLabel();
        phoceano5_txt = new javax.swing.JLabel();
        phoceano2_txt = new javax.swing.JLabel();
        phoceano4_txt = new javax.swing.JLabel();
        nomeoceano1_txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Oceanos");

        nomeoceano3_txt.setBackground(new java.awt.Color(255, 255, 51));
        nomeoceano3_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeoceano3_txt.setForeground(new java.awt.Color(255, 255, 0));
        nomeoceano3_txt.setText("null");

        nomeoceano2_txt.setBackground(new java.awt.Color(255, 255, 51));
        nomeoceano2_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeoceano2_txt.setForeground(new java.awt.Color(255, 255, 0));
        nomeoceano2_txt.setText("null");

        nomeoceano4_txt.setBackground(new java.awt.Color(255, 255, 51));
        nomeoceano4_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeoceano4_txt.setForeground(new java.awt.Color(255, 255, 0));
        nomeoceano4_txt.setText("null");

        nomeoceano5_txt.setBackground(new java.awt.Color(255, 255, 51));
        nomeoceano5_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeoceano5_txt.setForeground(new java.awt.Color(255, 255, 0));
        nomeoceano5_txt.setText("null");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Nome");

        jProgressBar1.setToolTipText("");
        jProgressBar1.setValue(120);

        jProgressBar2.setValue(82);

        jProgressBar3.setValue(90);

        jProgressBar4.setValue(72);

        jProgressBar5.setValue(107);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("PH");

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        phoceano1_txt.setBackground(new java.awt.Color(255, 255, 51));
        phoceano1_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoceano1_txt.setForeground(new java.awt.Color(255, 255, 0));
        phoceano1_txt.setText("null");
        phoceano1_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoceano1_txtMouseClicked(evt);
            }
        });

        phoceano3_txt.setBackground(new java.awt.Color(255, 255, 51));
        phoceano3_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoceano3_txt.setForeground(new java.awt.Color(255, 255, 0));
        phoceano3_txt.setText("null");
        phoceano3_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoceano3_txtMouseClicked(evt);
            }
        });

        phoceano5_txt.setBackground(new java.awt.Color(255, 255, 51));
        phoceano5_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoceano5_txt.setForeground(new java.awt.Color(255, 255, 0));
        phoceano5_txt.setText("null");
        phoceano5_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoceano5_txtMouseClicked(evt);
            }
        });

        phoceano2_txt.setBackground(new java.awt.Color(255, 255, 51));
        phoceano2_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoceano2_txt.setForeground(new java.awt.Color(255, 255, 0));
        phoceano2_txt.setText("null");
        phoceano2_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoceano2_txtMouseClicked(evt);
            }
        });

        phoceano4_txt.setBackground(new java.awt.Color(255, 255, 51));
        phoceano4_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoceano4_txt.setForeground(new java.awt.Color(255, 255, 0));
        phoceano4_txt.setText("null");
        phoceano4_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoceano4_txtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoceano4_txt)
                    .addComponent(phoceano2_txt)
                    .addComponent(phoceano5_txt)
                    .addComponent(phoceano3_txt)
                    .addComponent(phoceano1_txt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(phoceano1_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoceano2_txt)
                .addGap(8, 8, 8)
                .addComponent(phoceano3_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoceano4_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(phoceano5_txt))
        );

        nomeoceano1_txt.setBackground(new java.awt.Color(255, 255, 51));
        nomeoceano1_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeoceano1_txt.setForeground(new java.awt.Color(255, 255, 0));
        nomeoceano1_txt.setText("null");
        nomeoceano1_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeoceano1_txtMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Profundidade");

        btnvoltar.setText("Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nomeoceano2_txt)
                                                    .addComponent(nomeoceano1_txt))
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nomeoceano3_txt)
                                                    .addComponent(nomeoceano4_txt)
                                                    .addComponent(nomeoceano5_txt))
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jProgressBar4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(11, 11, 11)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addComponent(jLabel5)))
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel4)))))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnvoltar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeoceano1_txt))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeoceano2_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeoceano3_txt))
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeoceano4_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jProgressBar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeoceano5_txt))
                            .addComponent(jProgressBar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnvoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phoceano1_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoceano1_txtMouseClicked
        
    }//GEN-LAST:event_phoceano1_txtMouseClicked

    private void phoceano3_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoceano3_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phoceano3_txtMouseClicked

    private void phoceano5_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoceano5_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phoceano5_txtMouseClicked

    private void phoceano2_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoceano2_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phoceano2_txtMouseClicked

    private void phoceano4_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoceano4_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phoceano4_txtMouseClicked

    private void nomeoceano1_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeoceano1_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeoceano1_txtMouseClicked

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        dispose();
        new inicio_GUI().setVisible(true);
    }//GEN-LAST:event_btnvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oceanos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oceanos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oceanos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oceanos_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oceanos_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    public static javax.swing.JLabel nomeoceano1_txt;
    public static javax.swing.JLabel nomeoceano2_txt;
    public static javax.swing.JLabel nomeoceano3_txt;
    public static javax.swing.JLabel nomeoceano4_txt;
    public static javax.swing.JLabel nomeoceano5_txt;
    public static javax.swing.JLabel phoceano1_txt;
    public static javax.swing.JLabel phoceano2_txt;
    public static javax.swing.JLabel phoceano3_txt;
    public static javax.swing.JLabel phoceano4_txt;
    public static javax.swing.JLabel phoceano5_txt;
    // End of variables declaration//GEN-END:variables
}
