/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
/**
 *
 * @author netoh
 */
    import Controller.Database;
    import Controller.Rivers;
    import java.util.ArrayList;
    



public class Rios_GUI extends javax.swing.JFrame {
    
    public static ArrayList<Rivers> rivers = new ArrayList<>();

    public static void updatePHLabel(double madeiraPH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Rios_GUI
     */


            
    public Rios_GUI() {
        rivers = new Database().rivers;
        initComponents();
        loading();
    }
    
    public static void loading(){
        
        rio1_txt.setText(String.valueOf(rivers.get(0).pH));
        nomerio1_txt.setText(rivers.get(0).name);
    }



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rio3_txt = new javax.swing.JLabel();
        nomerio2_txt = new javax.swing.JLabel();
        rio4_txt = new javax.swing.JLabel();
        rio5_txt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rio1_txt = new javax.swing.JLabel();
        rio1_txt2 = new javax.swing.JLabel();
        rio1_txt3 = new javax.swing.JLabel();
        rio1_txt4 = new javax.swing.JLabel();
        rio1_txt6 = new javax.swing.JLabel();
        nomerio1_txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teste = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rios");

        rio3_txt.setBackground(new java.awt.Color(255, 255, 51));
        rio3_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio3_txt.setForeground(new java.awt.Color(255, 255, 0));
        rio3_txt.setText("São Francisco");

        nomerio2_txt.setBackground(new java.awt.Color(255, 255, 51));
        nomerio2_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomerio2_txt.setForeground(new java.awt.Color(255, 255, 0));
        nomerio2_txt.setText("Paraná");

        rio4_txt.setBackground(new java.awt.Color(255, 255, 51));
        rio4_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio4_txt.setForeground(new java.awt.Color(255, 255, 0));
        rio4_txt.setText("Tocantins");

        rio5_txt.setBackground(new java.awt.Color(255, 255, 51));
        rio5_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio5_txt.setForeground(new java.awt.Color(255, 255, 0));
        rio5_txt.setText("Madeira");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Nome");

        jProgressBar1.setToolTipText("");

        jProgressBar2.setValue(50);

        jProgressBar3.setValue(50);

        jProgressBar4.setValue(50);

        jProgressBar5.setValue(50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("PH");

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        rio1_txt.setBackground(new java.awt.Color(255, 255, 51));
        rio1_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio1_txt.setForeground(new java.awt.Color(255, 255, 0));
        rio1_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rio1_txtMouseClicked(evt);
            }
        });

        rio1_txt2.setBackground(new java.awt.Color(255, 255, 51));
        rio1_txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio1_txt2.setForeground(new java.awt.Color(255, 255, 0));
        rio1_txt2.setText("50%");
        rio1_txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rio1_txt2MouseClicked(evt);
            }
        });

        rio1_txt3.setBackground(new java.awt.Color(255, 255, 51));
        rio1_txt3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio1_txt3.setForeground(new java.awt.Color(255, 255, 0));
        rio1_txt3.setText("50%");
        rio1_txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rio1_txt3MouseClicked(evt);
            }
        });

        rio1_txt4.setBackground(new java.awt.Color(255, 255, 51));
        rio1_txt4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio1_txt4.setForeground(new java.awt.Color(255, 255, 0));
        rio1_txt4.setText("50%");
        rio1_txt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rio1_txt4MouseClicked(evt);
            }
        });

        rio1_txt6.setBackground(new java.awt.Color(255, 255, 51));
        rio1_txt6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rio1_txt6.setForeground(new java.awt.Color(255, 255, 0));
        rio1_txt6.setText("50%");
        rio1_txt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rio1_txt6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rio1_txt6)
                    .addComponent(rio1_txt4)
                    .addComponent(rio1_txt3)
                    .addComponent(rio1_txt2)
                    .addComponent(rio1_txt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rio1_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rio1_txt4)
                .addGap(8, 8, 8)
                .addComponent(rio1_txt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rio1_txt6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rio1_txt3))
        );

        nomerio1_txt.setBackground(new java.awt.Color(255, 255, 51));
        nomerio1_txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomerio1_txt.setForeground(new java.awt.Color(255, 255, 0));
        nomerio1_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomerio1_txtMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Profundidade");

        teste.setText("teste");
        teste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teste)
                .addGap(150, 150, 150))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomerio2_txt)
                                            .addComponent(nomerio1_txt))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rio3_txt)
                                            .addComponent(rio4_txt)
                                            .addComponent(rio5_txt))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jProgressBar4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(11, 11, 11)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(jLabel5)))
                                .addGap(45, 45, 45)
                                .addComponent(jLabel4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomerio1_txt))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomerio2_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rio3_txt))
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rio4_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jProgressBar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rio5_txt))
                            .addComponent(jProgressBar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(teste)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rio1_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rio1_txtMouseClicked
            Database.Rivers();    
            Object madeiraPH = null;
            rio1_txt.setText(String.valueOf(madeiraPH));
    }//GEN-LAST:event_rio1_txtMouseClicked

    private void nomerio1_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomerio1_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nomerio1_txtMouseClicked

    private void rio1_txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rio1_txt2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rio1_txt2MouseClicked

    private void rio1_txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rio1_txt3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rio1_txt3MouseClicked

    private void rio1_txt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rio1_txt4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rio1_txt4MouseClicked

    private void testeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testeActionPerformed
        
    }//GEN-LAST:event_testeActionPerformed

    private void rio1_txt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rio1_txt6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rio1_txt6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rios_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rios_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rios_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rios_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rios_GUI().setVisible(true);
            }
        });
    }

    public void recebendo(String recebe){
        rio1_txt.setText(recebe);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    public static javax.swing.JLabel nomerio1_txt;
    public static javax.swing.JLabel nomerio2_txt;
    public static javax.swing.JLabel rio1_txt;
    public static javax.swing.JLabel rio1_txt2;
    public static javax.swing.JLabel rio1_txt3;
    public static javax.swing.JLabel rio1_txt4;
    public static javax.swing.JLabel rio1_txt6;
    public static javax.swing.JLabel rio3_txt;
    public static javax.swing.JLabel rio4_txt;
    public static javax.swing.JLabel rio5_txt;
    private javax.swing.JButton teste;
    // End of variables declaration//GEN-END:variables
}
